apiVersion: 1

prune: true

deleteDatasources:
  - name: Postgres IoT
    orgId: 1

datasources:
  - name: Postgres IoT
    uid: ff7ghrnb3jxmoa
    type: postgres
    access: proxy
    orgId: 1
    isDefault: true
    editable: true

    url: postgres:5432
    database: iotdb
    user: iot

    secureJsonData:
      password: iotpass

    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
