{
 "title": "Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Avg temp per minute (agg table)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  window_start AS time,\r\n  avg_temp,\r\n  device_id\r\nFROM agg_readings_minute\r\nWHERE $__timeFilter(window_start)\r\nORDER BY window_start;"
    }
   ]
  },
  {
   "title": "Alerts list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS time,\r\n  device_id,\r\n  rule,\r\n  value,\r\n  threshold\r\nFROM alerts\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts DESC"
    }
   ]
  },
  {
   "title": "Raw temperature over time (per sensor)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ts AS time,\r\n  temperature,\r\n  device_id\r\nFROM raw_readings\r\nWHERE $__timeFilter(ts)\r\nORDER BY ts;"
    }
   ]
  }
 ]
}